 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/loads", type: :request do
  # Load. As you add validations to Load, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Load.create! valid_attributes
      get loads_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      load = Load.create! valid_attributes
      get load_url(load)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_load_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      load = Load.create! valid_attributes
      get edit_load_url(load)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Load" do
        expect {
          post loads_url, params: { load: valid_attributes }
        }.to change(Load, :count).by(1)
      end

      it "redirects to the created load" do
        post loads_url, params: { load: valid_attributes }
        expect(response).to redirect_to(load_url(Load.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Load" do
        expect {
          post loads_url, params: { load: invalid_attributes }
        }.to change(Load, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post loads_url, params: { load: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested load" do
        load = Load.create! valid_attributes
        patch load_url(load), params: { load: new_attributes }
        load.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the load" do
        load = Load.create! valid_attributes
        patch load_url(load), params: { load: new_attributes }
        load.reload
        expect(response).to redirect_to(load_url(load))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        load = Load.create! valid_attributes
        patch load_url(load), params: { load: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested load" do
      load = Load.create! valid_attributes
      expect {
        delete load_url(load)
      }.to change(Load, :count).by(-1)
    end

    it "redirects to the loads list" do
      load = Load.create! valid_attributes
      delete load_url(load)
      expect(response).to redirect_to(loads_url)
    end
  end
end
